[versions]
agp = "8.12.2"
gradle = "8.12.2"

[libraries]
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }


